Repository rxdcxdrnine/todo-list, pull requests merged in 2022-04, with the labels that each got.

#6 [BE] backend 디렉토리 추가
  backend/.keep
Labels: BE, chore

#5 [FE] 프론트엔드 디렉토리 추가
  frontend/index.html
Labels: FE, chore

#14 [BE] ER 다이어그램 및 스키마 작성
  backend/diagram.drawio
Labels: docs, BE

#15 [BE] 도메인 객체 다이어그램 그리기
  backend/diagram.drawio
Labels: docs, BE

#16 [BE] spring initializr를 이용해 스프링부트 프로젝트 생성
  backend/.gitignore
  backend/.keep
  backend/build.gradle
  backend/diagram.drawio
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/codesquad/todolist/TodolistApplicationTests.java
Labels: BE, feat

#17 [BE] 데이터베이스 생성 및 스프링부트 연결하기
  backend/README.md
  backend/build.gradle
  backend/docker/local-database.yml
  backend/src/main/resources/application.properties
Labels: BE, feat

#20 [FE] layout 생성
  frontend/README.md
  frontend/dist/01371ef659b72c37c0e9.png
  frontend/dist/0e2eddf15d840be42f97.png
  frontend/dist/1b6cf373ecf1bd2d4285.png
  frontend/dist/371a56678ff59e65a0ed.png
  frontend/dist/css/style.css
  frontend/dist/index.html
  frontend/dist/js/bundle.js
  frontend/dist/src/css/style.css
  frontend/dist/src/img/62c00551442b36ae2930610ce9328ad8.png
  frontend/dist/src/img/67ed9eecb3f3e6b4431590fc517180b7.png
  frontend/dist/src/img/af13822252b55ed90a2fc5818b1405e5.png
  frontend/dist/src/img/b214019be7c5f0b1df9a7d014e843df4.png
  frontend/dist/src/js/bundle.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/css/style.scss
  frontend/src/img/column_add.png
  frontend/src/img/column_add_blue.png
  frontend/src/img/column_delete.png
  frontend/src/img/column_delete_red.png
  frontend/src/img/menu_icon.png
  frontend/src/js/app.js
  frontend/src/scss/reset.scss
  frontend/src/scss/style.scss
  frontend/webpack.config.js
Labels: FE, feat

#21 [BE] 데이터베이스 DML,DDL 추가
  backend/diagram.drawio
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: BE, feat

#24 [BE] API 문서화를 위한 Swagger 설정 추가
  backend/build.gradle
  backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
Labels: BE, feat

#26 [BE] 1차 PR 리뷰 피드백 반영
  backend/diagram.drawio
  backend/docker/local-database.yml
  backend/src/main/resources/schema.sql
Labels: BE, fix

#27 [BE] 도메인 객체 추가 및 레이어 클래스 추가
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat

#28 [FE] HTML, SCSS 완료
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/close.png
  frontend/src/img/user.svg
  frontend/src/scss/reset.scss
  frontend/src/scss/style.scss
  frontend/webpack.config.js
Labels: FE, feat

#31 [BE] 카드 CREATE 기능 추가
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/util/GeneratedKeyHolderFactory.java
  backend/src/main/java/com/codesquad/todolist/util/KeyHolderFactory.java
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/card/integration/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat

#32 [BE] 카드 UPDATE 기능 추가
  backend/build.gradle
  backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/column/Column.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
  backend/src/main/java/com/codesquad/todolist/user/User.java
  backend/src/main/java/com/codesquad/todolist/user/UserRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/codesquad/todolist/TodolistApplicationTests.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardSetUp.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat

#46 [BE] 2차 PR 피드백 적용
  backend/build.gradle
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/exception/GlobalExceptionHandler.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, fix

#47 [FE] alert창 기본 동작 구현
  frontend/index.html
  frontend/src/js/Alert/AlertView.js
  frontend/src/js/Controller/Controller.js
  frontend/src/js/app.js
  frontend/src/js/utils/createTemplate.js
Labels: FE, feat

#50 [BE] 카드 삭제 기능 구현 및 테스트코드 작성
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat

#52 [BE] History 삽입 및 읽기 기능 추가
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryController.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryRepository.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryService.java
  backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
  backend/src/main/java/com/codesquad/todolist/history/domain/Action.java
  backend/src/main/java/com/codesquad/todolist/history/domain/Field.java
  backend/src/main/java/com/codesquad/todolist/history/domain/History.java
  backend/src/main/java/com/codesquad/todolist/history/domain/ModifiedField.java
  backend/src/main/java/com/codesquad/todolist/history/dto/HistoryResponse.java
  backend/src/main/java/com/codesquad/todolist/history/dto/ModifiedFieldResponse.java
  backend/src/main/java/com/codesquad/todolist/util/page/Criteria.java
  backend/src/main/java/com/codesquad/todolist/util/page/Slice.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/SetUp.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardSetUp.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryControllerTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/ModifiedFieldRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/history/unit/HistoryControllerTest.java
  backend/src/test/java/com/codesquad/todolist/history/unit/HistoryServiceTest.java
Labels: BE, feat

#56 [BE] DateTime 포맷 및 History 페이징 수정
  backend/src/main/java/com/codesquad/todolist/config/DateTimeConfig.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
  backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
  backend/src/main/java/com/codesquad/todolist/util/page/Slice.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/codesquad/todolist/history/unit/HistoryServiceTest.java
Labels: BE, fix

#54 [BE] 연결리스트 방식으로 카드 생성, 삭제, 이동 기능 구현
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat, fix

#58 [BE] Column 별로 Card 출력 기능 추가 및 Card CRUD 시 History 응답 기능 추가
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardResponse.java
  backend/src/main/java/com/codesquad/todolist/column/Column.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnController.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
  backend/src/main/java/com/codesquad/todolist/column/dto/ColumnResponse.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryController.java
  backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
  backend/src/main/java/com/codesquad/todolist/history/domain/ModifiedField.java
  backend/src/main/java/com/codesquad/todolist/util/page/Criteria.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/column/unit/ColumnServiceTest.java
Labels: BE, feat

#59 [FE] 드래그앤 드롭 기본 기능 구현(도착 잔상 및 맨끝에 추가 제외)
  frontend/src/js/app.js
  frontend/src/js/dragNdrop.js
  frontend/src/scss/style.scss
Labels: FE, feat

#57 [FE] 카드 추가 기능 구현
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Todo/Card/Model.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/Card/main.js
  frontend/src/js/Todo/Column/Model.js
  frontend/src/js/Todo/Column/View.js
  frontend/src/js/Todo/Column/main.js
  frontend/src/js/Todo/Model.js
  frontend/src/js/Todo/View.js
  frontend/src/js/Todo/main.js
  frontend/src/js/Utils/template.js
  frontend/src/js/app.js
  frontend/src/scss/style.scss
Labels: FE, feat

#62 [BE] API 문서화를 위한 Swagger 어노테이션 추가
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnController.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryController.java
Labels: BE, feat

#64 [BE] application.properties 에서 DB 계정 정보를 local, prod 로 분리
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application.properties
Labels: BE, chore

#65 [BE] application-prod.properties 내 계정 수정 및 swagger docs 수정
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/resources/application-prod.properties
Labels: BE, chore

#66 [BE] 카드 생성 시 검증 로직 추가
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: BE, feat

#73 [FE] 카드 삭제 기능 구현
  frontend/src/js/Alert/AlertView.js
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/Column/Model.js
  frontend/src/js/app.js
Labels: FE, feat

#75 [BE] 3차 PR 피드백 적용
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryService.java
Labels: BE, chore

#67 [FE] 카드 수정기능 구현
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/View.js
  frontend/src/scss/style.scss
Labels: FE, feat

#80 feat: [#77] WebMvcConfig 내 addCorsMapping 추가
  backend/src/main/java/com/codesquad/todolist/config/WebMvcConfig.java
Labels: BE, FE

#81 [BE] Update 시 PUT 대신 PATCH 방식을 사용하도록 변경
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
Labels: BE, fix

#83 Fe/feature/#78 column fetch
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Header/Model.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/Column/Model.js
  frontend/src/js/Todo/Column/View.js
  frontend/src/js/Todo/Column/main.js
  frontend/src/js/Todo/Model.js
  frontend/src/js/Utils/template.js
Labels: FE, feat

#79 [BE] 예외 처리와 에러 응답 구현
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/BundleResponse.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
  backend/src/main/java/com/codesquad/todolist/exception/BusinessException.java
  backend/src/main/java/com/codesquad/todolist/exception/ErrorCode.java
  backend/src/main/java/com/codesquad/todolist/exception/ErrorResponse.java
  backend/src/main/java/com/codesquad/todolist/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/codesquad/todolist/exception/NotFoundException.java
  backend/src/main/resources/data.sql
Labels: BE, feat

#84 [FE] 카드 추가, 수정, 삭제 요청 구현
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Utils/api.js
Labels: FE, feat

#85 [FE] 초기 히스토리 렌더
  frontend/src/js/Controller/Controller.js
  frontend/src/js/History/Model.js
  frontend/src/js/History/View.js
  frontend/src/js/History/main.js
  frontend/src/js/Utils/template.js
Labels: FE, feat

#76 [BE] ERD, schema 최신화
  backend/diagram.drawio
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryRepository.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: docs, BE

#87 [FE] 카드 추가, 수정, 삭제시 히스토리에 반영
  frontend/src/js/Controller/Controller.js
  frontend/src/js/History/Model.js
  frontend/src/js/History/View.js
  frontend/src/js/Utils/api.js
Labels: FE, feat

#88 [FE] 히스토리 렌더 완료
  frontend/src/js/Controller/Controller.js
  frontend/src/js/History/Model.js
  frontend/src/js/History/View.js
  frontend/src/js/Todo/Model.js
  frontend/src/js/Utils/api.js
  frontend/src/scss/style.scss
Labels: FE, feat

#90 [BE] 실패하는 테스트 코드 수정
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application.properties
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryRepositoryTest.java
Labels: BE, test

#92 docs: [#91] README 작성 - BC
  backend/README.md
Labels: docs, BE
